#
# Licensed under the EUPL, Version 1.2 or – as soon they will be approved by
# the European Commission - subsequent versions of the EUPL (the "Licence");
# You may not use this work except in compliance with the Licence.
# You may obtain a copy of the Licence at:
#
#   https://joinup.ec.europa.eu/software/page/eupl
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the Licence is distributed on an "AS IS" basis,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the Licence for the specific language governing permissions and
# limitations under the Licence.
#
#

camel.component.jetty.request-header-size=8192
camel.component.servlet.attachment-multipart-binding=true
camel.servlet.mapping.context-path=/services/*

chouette.export.days.back=30
chouette.export.days.foward=30
chouette.export.line.and.route.ids.cron.schedule=0+30+11+?+*+MON-FRI
chouette.generateVjMappingCsv=true
chouette.max.retries=5000
chouette.predefined.exports.mobiiti.technique.provider.schedule=0+0+0+1+1+?+2099=null
chouette.retry.delay=8000
chouette.stats.cache.refresh.quartz.trigger=cron=0+0+0+1+1+?+2099
chouette.stats.days=180
chouette.stats.validity.categories=60
chouette.storage.path=/tmp/lmd/chouette/
chouette.url=http://localhost:8080
chouette.validate.level1.autoStartup=true
chouette.validate.level1.cron.schedule=0+0+0+1+1+?+2099

client.name=lmd

oauth2-issuer=https://lumidata.dev.okina.fr/auth/realms/Mobi-iti
# OIDC Configuration
com.c4-soft.springaddons.oidc.ops[0].iss=${oauth2-issuer}
com.c4-soft.springaddons.oidc.ops[0].username-claim=preferred_username
# Authorities Configuration
com.c4-soft.springaddons.oidc.ops[0].authorities[0].prefix=
com.c4-soft.springaddons.oidc.ops[0].authorities[0].path[0]=$.realm_access.roles
com.c4-soft.springaddons.oidc.ops[0].authorities[0].path[1]=$.resource_access.*.roles

# Resource Server Configuration
com.c4-soft.springaddons.oidc.resourceserver.permit-all[0]=/services/timetable_admin/**
com.c4-soft.springaddons.oidc.resourceserver.permit-all[1]=/services/map_admin/**
com.c4-soft.springaddons.oidc.resourceserver.permit-all[2]=/scrape
com.c4-soft.springaddons.oidc.resourceserver.permit-all[3]=/ready
com.c4-soft.springaddons.oidc.resourceserver.permit-all[4]=/live


cron.get.missing.insee.code=0 0 12 ? * SUN

data.alert.expired.cron=0+0+5+?+*+MON

endpoints.jmx.enabled=false
endpoints.jolokia.enable=false

etcd.in.memory=true
etcd.url=http://notinuse

export-templates.api.url=http://0.0.0.0:8000/api/offre/1.0/admin/export-templates
fares.url=http://localhost:8095/fares-referential/fares/

google.publish.public=true

gtfs.basic.export.merged.file.name=mosaic-aggregated-gtfs.zip
gtfs.export.download.directory=/tmp/lmd/chouette/mobiiti_technique
gtfs.norway.merged.file.name=mosaic-aggregated-extended-gtfs.zip

hazelcast.external.service.name=0+15+23+?+*+MON-FRI

idempotent.skip=false

import-configuration.api.url=http://localhost:8081/Okina/REST/admin/import-configuration

ineo.sic.enabled=true

lug.url=http://localhost:28080

marduk.gtfs-import-filter-location-type-enabled=true
marduk.shutdown.timeout=1
marduk.upload.public.path=pan
marduk.validate.auto.exports=true

nabu.url=http://localhost:10001

netex.export.download.directory=/tmp/lmd/chouette/mobiiti_technique
netex.export.file=null
netex.export.path=naq-aggregated-netex.zip
netex.merge.delay.before.checks=60000
netex.merge.max.retries=720

nri.ftp.auto.import=true
nri.ftp.folder=rutedata
nri.ftp.host=127.0.0.1
nri.ftp.initialDelay=1s
nri.ftp.password=toChange
nri.ftp.username=toChange

organisations.api.url=http://localhost:8000/api/organisations/1.0/

parking.predefined.exports.mobiiti.technique.schedule=0+0+0+1+1+?+2099

pigma.metadata.mail=test@test.fr
pigma.upload.path=pigma

providers.api.url=http://localhost:8000/api/providers/1.0/

rutebanken.autotransferdata.enabled=false
rutebanken.route.singleton.policy.ignore=false

server.admin.host=0.0.0.0
server.name=local
server.port=8687

sftp.autoStartup=false
sftp.delay=30s
sftp.host=fakeHost
sftp.keyfile=src/test/resources/dummy.pem
sftp.known.hosts.file=$HOME/.ssh/known_hosts
sftp.pigma.host=www.fakehost.org
sftp.pigma.login=null
sftp.pigma.passphrase=null
sftp.pigma.path=/fake/path
sftp.pigma.port=1234
sftp.pigma.privateKey=./pigma/key
sftp.pigma.protocol=sftp

simulation.export.type=SFTP
simulation.ftp.password=to-be-replaced
simulation.ftp.port=22
simulation.ftp.targetDirectory=/tmp
simulation.ftp.url=to-be-replaced
simulation.ftp.user=to-be-replaced
simulation.name=simulation

spring.application.name=Marduk
spring.artemis.broker-url=tcp://localhost:61616
spring.artemis.mode=native
spring.artemis.password=null
spring.artemis.user=null
spring.datasource.password=marduk
spring.datasource.url=jdbc:postgresql://localhost:5440/marduk
spring.datasource.username=marduk
spring.jms.pub-sub-domain=false
spring.mail.host=test
spring.mail.password=null
spring.mail.port=12
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.to=test
spring.mail.username=null
spring.main.allow-bean-definition-overriding=true
spring.main.sources=no.rutebanken.marduk
spring.profiles.active=in-memory-blobstore
spring.quartz.auto-startup=false
spring.quartz.jdbc.initialize-schema=never
spring.quartz.jdbc.platform=postgresql
spring.quartz.job-store-type=jdbc
spring.quartz.jobStore.driverDelegateClass=org.postgresql.Driver
spring.quartz.scheduler-name=QuartzScheduler-Import-Configuration
spring.servlet.multipart.enabled=true

stop-places-export.api.url=http://localhost:8000/api/stop_places/1.0/netex/export

superspace.name=mobiiti

tiamat.storage.path=/tmp/lmd/tiamat/
tiamat.url=http://localhost:8000/api/stop_places/1.0

upload.pigma.cron=0+0+0+1+1+?+2099
gtfs.fares.export.dir=/tmp/generatedFares/gtfsv2
